import { Plant } from '../types';

const plants: Plant[] = [
  {
    num: 1,
    name: 'Button Fern',
    count: 6,
    price: 100,
    size: 'Medium',
    color: 'Terracotta',
    dif: 'For Experts',
    pet: false,
  },
  {
    num: 2,
    name: 'Ficus Burgundy',
    count: 3,
    price: 90,
    size: 'Medium',
    color: 'Terracotta',
    dif: 'For Begginers',
    pet: false,
  },
  {
    num: 3,
    name: 'Fiddle Leaf Fig',
    count: 7,
    price: 20,
    size: 'Small',
    color: 'White',
    dif: 'For Begginers',
    pet: false,
  },
  {
    num: 4,
    name: 'Hoya Heart',
    count: 2,
    price: 25,
    size: 'Small',
    color: 'Black',
    dif: 'For Experts',
    pet: false,
  },
  {
    num: 5,
    name: 'Large Monstera',
    count: 1,
    price: 200,
    size: 'Large',
    color: 'Terracotta',
    dif: 'For Experts',
    pet: false,
  },
  {
    num: 6,
    name: 'Monstera',
    count: 3,
    price: 100,
    size: 'Medium',
    color: 'White',
    dif: 'For Experts',
    pet: false,
  },
  {
    num: 7,
    name: 'Pothos',
    count: 8,
    price: 20,
    size: 'Small',
    color: 'White',
    dif: 'For Experts',
    pet: false,
  },
  {
    num: 8,
    name: 'Calathea Orbifolia',
    count: 10,
    price: 25,
    size: 'Small',
    color: 'White',
    dif: 'For Experts',
    pet: true,
  },
  {
    num: 9,
    name: 'Large Fan Palm',
    count: 3,
    price: 220,
    size: 'Large',
    color: 'Terracotta',
    dif: 'For Begginers',
    pet: true,
  },
  {
    num: 10,
    name: 'Leaf Fig Tree',
    count: 8,
    price: 50,
    size: 'Medium',
    color: 'Terracotta',
    dif: 'For Experts',
    pet: true,
  },
  {
    num: 11,
    name: 'Zamioculcas',
    count: 9,
    price: 40,
    size: 'Small',
    color: 'Black',
    dif: 'For Begginers',
    pet: false,
  },
  {
    num: 12,
    name: 'Large Snake Plant',
    count: 7,
    price: 90,
    size: 'Large',
    color: 'White',
    dif: 'For Begginers',
    pet: false,
  },
  {
    num: 13,
    name: 'Large Majesty Palm',
    count: 10,
    price: 120,
    size: 'Large',
    color: 'Terracotta',
    dif: 'For Experts',
    pet: true,
  },
  {
    num: 14,
    name: 'Money Tree',
    count: 1,
    price: 70,
    size: 'Small',
    color: 'White',
    dif: 'For Experts',
    pet: true,
  },
  {
    num: 15,
    name: 'Parlor Palm',
    count: 1,
    price: 80,
    size: 'Medium',
    color: 'Black',
    dif: 'For Experts',
    pet: true,
  },
  {
    num: 16,
    name: 'Snake Plant',
    count: 5,
    price: 60,
    size: 'Small',
    color: 'Black',
    dif: 'For Begginers',
    pet: true,
  },
  {
    num: 17,
    name: 'Philodendron Birkin',
    count: 2,
    price: 40,
    size: 'Small',
    color: 'White',
    dif: 'For Begginers',
    pet: false,
  },
  {
    num: 18,
    name: 'Silver Satin',
    count: 6,
    price: 40,
    size: 'Small',
    color: 'Black',
    dif: 'For Begginers',
    pet: false,
  },
  {
    num: 19,
    name: 'Peperomia',
    count: 10,
    price: 70,
    size: 'Small',
    color: 'Terracotta',
    dif: 'For Experts',
    pet: true,
  },
  {
    num: 20,
    name: 'Echeveria Lola',
    count: 1,
    price: 30,
    size: 'Small',
    color: 'White',
    dif: 'For Begginers',
    pet: true,
  },
  {
    num: 21,
    name: 'Spotted Orchid',
    count: 1,
    price: 25,
    size: 'Medium',
    color: 'White',
    dif: 'For Experts',
    pet: true,
  },
];

export default plants;